### ISSUE TITLE
Redux를 사용한 CRUD 만들기

### ISSUE THREAD

**Issue by reality023** [reality023/Untitled#4]
reality023 - 리덕스 기본 코드 세팅
proamateur92 - CRUD 코드 작성

**Comment by proamateur92** [comment]
1. 글 작성 시 이미지의 경로가 로컬 주소로  등록되고 있습니다.
->  main 페이지에서 이미지 출력되지 않습니다.
따라서 글을 작성할 때 임시로 배경이미지 경로를 default 값으로 하드코딩 해놓았습니다.

2. 글 작성, 글 수정의 페이지 호출 경로가 같으습니다.
그러나 사용자의 글 작성, 글 수정 페이지 이동을 구분할 수 있는 데이터 값이 아직 존재하지 않아 글 쓰기 기능만 구현하였습니다.

3. 확인 후 피드백 부탁드립니다.
